version: 3.2.0

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/root/app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/hello"]
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      DB_URL: host=db port=5432 user=postgres dbname=cms-db sslmode=disable password=postgres
      CORS_ALLOW_ORIGIN: http://localhost:3000 http://localhost:8000

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: cms-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
